apiVersion: v1
kind: Service
metadata:
  name: nodeexporter-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      name: http
  selector:
    role: nodeexporter
