apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  selector:
    app: prometheus-service
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 9090
      name: http